### ISSUE TITLE
Calibration data are not supported with OAK-D S2

### ISSUE THREAD

**Issue by alessiograncini** [luxonis/depthai-core-example#3]
`[system] [warning] Device contains calibration data of version 1437204487 which is not supported in this version of depthai
`

**Comment by SzabolcsGergely** [comment]
@alessiograncini depthai-core submodule was outdated (release 2.15.1 wich doesn't contain newest calibration model). [Updated](https://github.com/luxonis/depthai-core-example/commit/1731bf8e10fedf955befe01d30f2b14cb02d0cff) to 2.17.1, please do a `git pull`
